name: mcts_interpretability

channels:
  - conda-forge

dependencies:
  - python>=3.10
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - torch
  - tqdm
  - transformers
  - pip:
    - typed-argument-parser
